In [1]:
from pandas import *
from numpy.random import *
from numpy import *
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

data_frame= read_csv('archive/zomato.csv',engine='python',index_col=0,encoding = 'unicode_escape')
country=read_excel('archive/Country-Code.xlsx',index_col=0)

In [2]:
country

                     Country
Country Code
1                      India
14                 Australia
30                    Brazil
37                    Canada
94                 Indonesia
148              New Zealand
162              Phillipines
166                    Qatar
184                Singapore
189             South Africa
191                Sri Lanka
208                   Turkey
214                      UAE
215           United Kingdom
216            United States

In [3]:
data_frame.head(5)

,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
Restaurant ID,,,,,,,,,,,,,,,,,,,,
6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,1200,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.584450,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [4]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9551 entries, 6317637 to 5927402
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant Name       9551 non-null   object
 1   Country Code          9551 non-null   int64
 2   City                  9551 non-null   object
 3   Address               9551 non-null   object
 4   Locality              9551 non-null   object
 5   Locality Verbose      9551 non-null   object
 6   Longitude             9551 non-null   float64
 7   Latitude              9551 non-null   float64
 8   Cuisines              9542 non-null   object
 9   Average Cost for two  9551 non-null   int64
 10  Currency              9551 non-null   object
 11  Has Table booking     9551 non-null   object
 12  Has Online delivery   9551 non-null   object
 13  Is delivering now     9551 non-null   object
 14  Switch to order menu  9551 non-null   object
 15  Price range           9551 non-null   int64
 16  Aggregate rating      9551 non-null   float64
 17  Rating color          9551 non-null   object
 18  Rating text           9551 non-null   object
 19  Votes                 9551 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 1.5+ MB

In [5]:
data_frame.describe()

,Country Code,Longitude,Latitude,Average Cost for two,Price range,Aggregate rating,Votes
count,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000,9551.000000
mean,18.365616,64.126574,25.854381,1199.210763,1.804837,2.666370,156.909748
std,56.750546,41.467058,11.007935,16121.183073,0.905609,1.516378,430.169145
min,1.000000,-157.948486,-41.330428,0.000000,1.000000,0.000000,0.000000
25%,1.000000,77.081343,28.478713,250.000000,1.000000,2.500000,5.000000
50%,1.000000,77.191964,28.570469,400.000000,2.000000,3.200000,31.000000
75%,1.000000,77.282006,28.642758,700.000000,2.000000,3.700000,131.000000
max,216.000000,174.832089,55.976980,800000.000000,4.000000,4.900000,10934.000000

In [6]:
import json 
from pandas.io.json import json_normalize 

with open('archive/file2.json') as f:
  d = json.load(f)

nycphil = json_normalize(d)
nycphil.head()

,results_found,results_start,results_shown,restaurants
0,1263908,21,20,"[{'restaurant': {'R': {'res_id': 16668008}, 'a..."
1,1263908,21,20,"[{'restaurant': {'R': {'res_id': 16668008}, 'a..."
2,1263908,21,20,"[{'restaurant': {'R': {'res_id': 16668008}, 'a..."
3,1263908,21,20,"[{'restaurant': {'R': {'res_id': 16668008}, 'a..."
4,1263908,21,20,"[{'restaurant': {'R': {'res_id': 16668008}, 'a..."

In [7]:
import json 
from pandas.io.json import json_normalize 

with open('archive/file2.json') as f:
    d = json.load(f)

sam_json = json_normalize(d[0]["restaurants"])
sam_json.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 34 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   restaurant.R.res_id                      20 non-null     int64
 1   restaurant.apikey                        20 non-null     object
 2   restaurant.id                            20 non-null     object
 3   restaurant.name                          20 non-null     object
 4   restaurant.url                           20 non-null     object
 5   restaurant.location.address              20 non-null     object
 6   restaurant.location.locality             20 non-null     object
 7   restaurant.location.city                 20 non-null     object
 8   restaurant.location.city_id              20 non-null     int64
 9   restaurant.location.latitude             20 non-null     object
 10  restaurant.location.longitude            20 non-null     object
 11  restaurant.location.zipcode              20 non-null     object
 12  restaurant.location.country_id           20 non-null     int64
 13  restaurant.location.locality_verbose     20 non-null     object
 14  restaurant.switch_to_order_menu          20 non-null     int64
 15  restaurant.cuisines                      20 non-null     object
 16  restaurant.average_cost_for_two          20 non-null     int64
 17  restaurant.price_range                   20 non-null     int64
 18  restaurant.currency                      20 non-null     object
 19  restaurant.offers                        20 non-null     object
 20  restaurant.thumb                         20 non-null     object
 21  restaurant.user_rating.aggregate_rating  20 non-null     object
 22  restaurant.user_rating.rating_text       20 non-null     object
 23  restaurant.user_rating.rating_color      20 non-null     object
 24  restaurant.user_rating.votes             20 non-null     object
 25  restaurant.photos_url                    20 non-null     object
 26  restaurant.menu_url                      20 non-null     object
 27  restaurant.featured_image                20 non-null     object
 28  restaurant.has_online_delivery           20 non-null     int64
 29  restaurant.is_delivering_now             20 non-null     int64
 30  restaurant.deeplink                      20 non-null     object
 31  restaurant.has_table_booking             20 non-null     int64
 32  restaurant.events_url                    20 non-null     object
 33  restaurant.establishment_types           20 non-null     object
dtypes: int64(9), object(25)
memory usage: 5.4+ KB

In [8]:
sam_json["restaurant.id"]=sam_json["restaurant.id"].astype(int)

In [9]:
sam_json[sam_json["restaurant.id"]!=sam_json["restaurant.R.res_id"]]

Empty DataFrame
Columns: [restaurant.R.res_id, restaurant.apikey, restaurant.id, restaurant.name, restaurant.url, restaurant.location.address, restaurant.location.locality, restaurant.location.city, restaurant.location.city_id, restaurant.location.latitude, restaurant.location.longitude, restaurant.location.zipcode, restaurant.location.country_id, restaurant.location.locality_verbose, restaurant.switch_to_order_menu, restaurant.cuisines, restaurant.average_cost_for_two, restaurant.price_range, restaurant.currency, restaurant.offers, restaurant.thumb, restaurant.user_rating.aggregate_rating, restaurant.user_rating.rating_text, restaurant.user_rating.rating_color, restaurant.user_rating.votes, restaurant.photos_url, restaurant.menu_url, restaurant.featured_image, restaurant.has_online_delivery, restaurant.is_delivering_now, restaurant.deeplink, restaurant.has_table_booking, restaurant.events_url, restaurant.establishment_types]
Index: []

[0 rows x 34 columns]

In [10]:
rename={'restaurant.id': 'Restaurant ID', 'restaurant.name': 'Restaurant Name', 
 'restaurant.location.address': 'Address', 'restaurant.location.locality': 'Locality', 
 'restaurant.location.city': 'City', 'restaurant.location.latitude': 'Latitude', 
 'restaurant.location.longitude': 'Longitude', 'restaurant.location.country_id': 'Country Code',
 'restaurant.switch_to_order_menu': 'Switch to order menu', 'restaurant.cuisines': 'Cuisines',
 'restaurant.average_cost_for_two': 'Average Cost for two', 'restaurant.price_range': 'Price range',
 "restaurant.currency":"Currency", 'restaurant.user_rating.aggregate_rating':'Aggregate rating',
 'restaurant.user_rating.rating_text':'Rating text','restaurant.user_rating.rating_color':'Rating color',
 'restaurant.user_rating.votes':'Votes','restaurant.has_online_delivery':'Has Online delivery',
 'restaurant.is_delivering_now':'Is delivering now','restaurant.has_table_booking':'Has Table booking'
 }

In [11]:
all_col=set(sam_json.columns)
drop=list(all_col-(all_col&set(rename.keys())))

In [12]:
sam_json=sam_json.drop(drop,axis=1).rename(columns=rename).set_index('Restaurant ID')

In [13]:
sam_json.head(5)

,Restaurant Name,Address,Locality,City,Latitude,Longitude,Country Code,Switch to order menu,Cuisines,Average Cost for two,Price range,Currency,Aggregate rating,Rating text,Rating color,Votes,Has Online delivery,Is delivering now,Has Table booking
Restaurant ID,,,,,,,,,,,,,,,,,,,
16668008,Arigato Sushi,"14 Second Ave North, Yorkton, SK S3N 1G1",Yorkton,Yorkton,51.2106824000,-102.4613173000,37,0,Asian,25,2,$,3.3,Average,CDD614,26,0,0,0
801690,Mocha,"CP-1, 2nd Floor, Anand Plaza, Viram Khand-1, N...",Gomti Nagar,Lucknow,26.8528099000,81.0011849000,1,0,"Cafe, Italian, Continental",800,3,Rs.,4.6,Excellent,3F7E00,567,0,0,0
17558738,Blue House Cafe,"919 Bridge St, Vernonia, OR 97064",Vernonia,Vernonia,45.8586670000,-123.1954368000,216,0,"Coffee and Tea, Mediterranean",10,1,$,4.3,Very Good,5BA829,88,0,0,0
16611701,Star Buffet,"58 Hanbury St, Mayfield, NSW",Mayfield,Mayfield,-32.8991780000,151.7343832000,14,0,Asian,20,2,$,2.9,Average,FFBA00,11,0,0,0
2100784,11th Avenue Cafe Bistro,"Opposite Assam State Museum, Dighalipukhuri, T...",Uzan Bazaar,Guwahati,26.1860014826,91.7523143068,1,0,"Cafe, American, Italian, Continental",400,2,Rs.,4.1,Very Good,5BA829,377,0,0,0

In [14]:
combined_dataframe=concat([data_frame,sam_json])
combined_dataframe.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 9571 entries, 6317637 to 17211719
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant Name       9571 non-null   object
 1   Country Code          9571 non-null   int64
 2   City                  9571 non-null   object
 3   Address               9571 non-null   object
 4   Locality              9571 non-null   object
 5   Locality Verbose      9551 non-null   object
 6   Longitude             9571 non-null   object
 7   Latitude              9571 non-null   object
 8   Cuisines              9562 non-null   object
 9   Average Cost for two  9571 non-null   int64
 10  Currency              9571 non-null   object
 11  Has Table booking     9571 non-null   object
 12  Has Online delivery   9571 non-null   object
 13  Is delivering now     9571 non-null   object
 14  Switch to order menu  9571 non-null   object
 15  Price range           9571 non-null   int64
 16  Aggregate rating      9571 non-null   object
 17  Rating color          9571 non-null   object
 18  Rating text           9571 non-null   object
 19  Votes                 9571 non-null   object
dtypes: int64(3), object(17)
memory usage: 1.5+ MB

In [15]:
combined_dataframe.describe()

       Country Code  Average Cost for two  Price range
count   9571.000000           9571.000000  9571.000000
mean      18.518023           1197.028315     1.805872
std       56.958785          16104.404230     0.905995
min        1.000000              0.000000     1.000000
25%        1.000000            250.000000     1.000000
50%        1.000000            400.000000     2.000000
75%        1.000000            700.000000     2.000000
max      216.000000         800000.000000     4.000000

In [16]:
combined_dataframe.head()

,Restaurant Name,Country Code,City,Address,Locality,Locality Verbose,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes
Restaurant ID,,,,,,,,,,,,,,,,,,,,
6317637,Le Petit Souffle,162,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City","Century City Mall, Poblacion, Makati City, Mak...",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314
6304287,Izakaya Kikufuji,162,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City","Little Tokyo, Legaspi Village, Makati City, Ma...",121.014101,14.553708,Japanese,1200,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591
6300002,Heat - Edsa Shangri-La,162,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City","Edsa Shangri-La, Ortigas, Mandaluyong City, Ma...",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270
6318506,Ooma,162,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365
6314302,Sambo Kojin,162,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City","SM Megamall, Ortigas, Mandaluyong City, Mandal...",121.057508,14.58445,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229

In [17]:
data_combine_frame=[]
error_load=[]
def combine_data(file):
  global di
  loaded_file = json.load(open(file))
  for d in loaded_file:
    try:
      sam_json = json_normalize(d["restaurants"])
      sam_json["restaurant.id"]=sam_json["restaurant.id"].astype(int)
      sam_json=sam_json.drop(drop,axis=1).rename(columns=rename).set_index('Restaurant ID')
      data_combine_frame.append(sam_json)
    except KeyError:
      error_load.append(d)
      pass

In [18]:
import glob
json_files = glob.glob("archive/*.json")
for file in json_files:
  combine_data(file)

In [19]:
error_load

[{'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'results_found': 0,
  'restaurants': [],
  'results_shown': 0,
  'results_start': '1'},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},
 {'message': 'API limit exceeded', 'code': 440, 'status': ''},

In [20]:
data_combine_frame=[data_frame]+data_combine_frame
data_warehouse=concat(data_combine_frame)

In [21]:
data_warehouse.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39304 entries, 6317637 to 17582499
Data columns (total 24 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Restaurant Name            39304 non-null  object
 1   Country Code               39304 non-null  int64
 2   City                       39304 non-null  object
 3   Address                    39304 non-null  object
 4   Locality                   39304 non-null  object
 5   Locality Verbose           9551 non-null   object
 6   Longitude                  39304 non-null  object
 7   Latitude                   39304 non-null  object
 8   Cuisines                   39295 non-null  object
 9   Average Cost for two       39304 non-null  int64
 10  Currency                   39304 non-null  object
 11  Has Table booking          39304 non-null  object
 12  Has Online delivery        39304 non-null  object
 13  Is delivering now          39304 non-null  object
 14  Switch to order menu       39304 non-null  object
 15  Price range                39304 non-null  int64
 16  Aggregate rating           39304 non-null  object
 17  Rating color               39304 non-null  object
 18  Rating text                39304 non-null  object
 19  Votes                      39304 non-null  object
 20  restaurant.book_url        4291 non-null   object
 21  restaurant.zomato_events   1835 non-null   object
 22  restaurant.order_deeplink  58 non-null     object
 23  restaurant.order_url       58 non-null     object
dtypes: int64(3), object(21)
memory usage: 7.5+ MB

In [22]:
data_warehouse["Country Code"].unique()

array([162,  30, 216,  14,  37, 184, 214,   1,  94, 148, 215, 166, 189,
       191, 208,  17], dtype=int64)

In [23]:
data_warehouse["Currency"].unique()

array(['Botswana Pula(P)', 'Brazilian Real(R$)', 'Dollar($)',
       'Emirati Diram(AED)', 'Indian Rupees(Rs.)',
       'Indonesian Rupiah(IDR)', 'NewZealand($)', 'Pounds(\x8c£)',
       'Qatari Rial(QR)', 'Rand(R)', 'Sri Lankan Rupee(LKR)',
       'Turkish Lira(TL)', 'Rs.', 'AED', '$', 'LKR', 'TL', '£', 'QR', 'P',
       'R', 'R$', 'NZ$', '', 'IDR'], dtype=object)

In [24]:
data_warehouse["Currency"].replace(["Pounds(��)","NewZealand($)"],["Pounds(£)","NewZealand(NZ$)"],inplace=True)

In [25]:
data_warehouse["Currency"].unique()

array(['Botswana Pula(P)', 'Brazilian Real(R$)', 'Dollar($)',
       'Emirati Diram(AED)', 'Indian Rupees(Rs.)',
       'Indonesian Rupiah(IDR)', 'NewZealand(NZ$)', 'Pounds(\x8c£)',
       'Qatari Rial(QR)', 'Rand(R)', 'Sri Lankan Rupee(LKR)',
       'Turkish Lira(TL)', 'Rs.', 'AED', '$', 'LKR', 'TL', '£', 'QR', 'P',
       'R', 'R$', 'NZ$', '', 'IDR'], dtype=object)

In [26]:
cur=data_warehouse["Currency"].unique()
for i in cur:
  try:
    data_warehouse["Currency"].replace(i.split("(")[1].split(")")[0],i,inplace=True)
  except Exception:
    pass
data_warehouse["Currency"].unique()

array(['Botswana Pula(P)', 'Brazilian Real(R$)', 'Dollar($)',
       'Emirati Diram(AED)', 'Indian Rupees(Rs.)',
       'Indonesian Rupiah(IDR)', 'NewZealand(NZ$)', 'Pounds(\x8c£)',
       'Qatari Rial(QR)', 'Rand(R)', 'Sri Lankan Rupee(LKR)',
       'Turkish Lira(TL)', '£', ''], dtype=object)

In [27]:
data_warehouse["Price range"].unique()

array([3, 4, 2, 1], dtype=int64)

In [28]:
data_warehouse["Has Table booking"].unique()

array(['Yes', 'No', 1, 0], dtype=object)

In [29]:
data_warehouse["Has Table booking"].replace([1,0],["Yes","No"],inplace=True)
data_warehouse["Has Table booking"].unique()

array(['Yes', 'No'], dtype=object)

In [30]:
data_warehouse["Has Online delivery"].replace([1,0],["Yes","No"],inplace=True)
data_warehouse["Is delivering now"].replace([1,0],["Yes","No"],inplace=True)
data_warehouse["Switch to order menu"].replace([1,0],["Yes","No"],inplace=True)

In [31]:
data_warehouse=merge(data_warehouse, country, how="left", on="Country Code")
data_warehouse["Country"].unique()

array(['Phillipines', 'Brazil', 'United States', 'Australia', 'Canada',
       'Singapore', 'UAE', 'India', 'Indonesia', 'New Zealand',
       'United Kingdom', 'Qatar', 'South Africa', 'Sri Lanka', 'Turkey',
       nan], dtype=object)

In [32]:
data_warehouse.drop(["restaurant.order_url","restaurant.order_deeplink","restaurant.zomato_events","restaurant.book_url","Locality Verbose","Country Code"],axis=1,inplace=True)

In [33]:
data_warehouse.head()

,Restaurant Name,City,Address,Locality,Longitude,Latitude,Cuisines,Average Cost for two,Currency,Has Table booking,Has Online delivery,Is delivering now,Switch to order menu,Price range,Aggregate rating,Rating color,Rating text,Votes,Country
0,Le Petit Souffle,Makati City,"Third Floor, Century City Mall, Kalayaan Avenu...","Century City Mall, Poblacion, Makati City",121.027535,14.565443,"French, Japanese, Desserts",1100,Botswana Pula(P),Yes,No,No,No,3,4.8,Dark Green,Excellent,314,Phillipines
1,Izakaya Kikufuji,Makati City,"Little Tokyo, 2277 Chino Roces Avenue, Legaspi...","Little Tokyo, Legaspi Village, Makati City",121.014101,14.553708,Japanese,1200,Botswana Pula(P),Yes,No,No,No,3,4.5,Dark Green,Excellent,591,Phillipines
2,Heat - Edsa Shangri-La,Mandaluyong City,"Edsa Shangri-La, 1 Garden Way, Ortigas, Mandal...","Edsa Shangri-La, Ortigas, Mandaluyong City",121.056831,14.581404,"Seafood, Asian, Filipino, Indian",4000,Botswana Pula(P),Yes,No,No,No,4,4.4,Green,Very Good,270,Phillipines
3,Ooma,Mandaluyong City,"Third Floor, Mega Fashion Hall, SM Megamall, O...","SM Megamall, Ortigas, Mandaluyong City",121.056475,14.585318,"Japanese, Sushi",1500,Botswana Pula(P),No,No,No,No,4,4.9,Dark Green,Excellent,365,Phillipines
4,Sambo Kojin,Mandaluyong City,"Third Floor, Mega Atrium, SM Megamall, Ortigas...","SM Megamall, Ortigas, Mandaluyong City",121.057508,14.58445,"Japanese, Korean",1500,Botswana Pula(P),Yes,No,No,No,4,4.8,Dark Green,Excellent,229,Phillipines

In [34]:
data_warehouse.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 39304 entries, 0 to 39303
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Restaurant Name       39304 non-null  object
 1   City                  39304 non-null  object
 2   Address               39304 non-null  object
 3   Locality              39304 non-null  object
 4   Longitude             39304 non-null  object
 5   Latitude              39304 non-null  object
 6   Cuisines              39295 non-null  object
 7   Average Cost for two  39304 non-null  int64
 8   Currency              39304 non-null  object
 9   Has Table booking     39304 non-null  object
 10  Has Online delivery   39304 non-null  object
 11  Is delivering now     39304 non-null  object
 12  Switch to order menu  39304 non-null  object
 13  Price range           39304 non-null  int64
 14  Aggregate rating      39304 non-null  object
 15  Rating color          39304 non-null  object
 16  Rating text           39304 non-null  object
 17  Votes                 39304 non-null  object
 18  Country               39284 non-null  object
dtypes: int64(2), object(17)
memory usage: 6.0+ MB

In [35]:
data_warehouse.describe()

       Average Cost for two   Price range
count          39304.000000  39304.000000
mean            2217.672756      2.091441
std            17750.203378      0.956545
min                0.000000      1.000000
25%              120.000000      1.000000
50%              450.000000      2.000000
75%              800.000000      3.000000
max           800000.000000      4.000000

In [36]:
data_warehouse.to_csv('DataWarehouse.csv',index=False)